version: '3.9'
services:
  mysql:
    image: mysql
    container_name: soft-mix-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/data/db
