### Запрос всех категорий
GET http://localhost:4000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyOTI0MmJkZDMwOWU1NmI3NWZjYjZkZSIsImVtYWlsIjoiYW5kcmV5QGV4YW1wbGUucnUiLCJpYXQiOjE2NTM3NjYzMDUsImV4cCI6MTY1Mzc2NzIwNX0.JEJ2zfJJKkmUqr50nOc0oW9hnYZ2qf4wzxvhMEtTU0k
Accept: application/json

### Добавление новой категории
POST http://localhost:4000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

{
  "title": "Товары"
}
